### ISSUE TITLE
fix: remove autoload.php form Give core vendor folder

### ISSUE THREAD

**Issue by ravinderk** [impress-org/plugin-release-shells#5]
We are using composer to only manage updates of PHP libraries. for example: In Give 2.4.0, we will start loading `tcpdf` on for export setting page with direct vendor directory PHP, so no need to `autoload.php`.

We do not want anyone to use `autoload.php` to prevent conflict and performance issue.

https://github.com/impress-org/plugin-release-shells/blob/68f6c23b248583a02634719e24b4b98d49af8cb0/give-core-releases.sh#L102

for ref: https://github.com/impress-org/give/compare/8d0a91b8a910...976df1021b56

**Comment by DevinWalker** [comment]
Maybe we'll use it in the future. I don't this we need to remove it.
